Pegasus
FU-Hagen-Discord/halloween pull request #7
Opened 2022-09-27 19:20 UTC by Pegasus01123

Neue Türen und das minus bei den Süßigkeiten berichtigt

2022-09-28 05:44 UTC, Pegasus01123 commented
Ursprünglich war dieser branch für neue Türen und Storyelemente. die Änderung am code hat sich leider hier mit eingeschlichen, da ich nicht aufgepasst habe, wo ich mich gerade befinde. Ich habe bei allen commits jeweils die Zeilen nummern angegeben, in denen ich etwas geändert habe.

2022-10-05 08:12 UTC, dnns01 requested changes

2022-10-05 08:12 UTC, dnns01 commented on data/story.json
> +        "text": "Die nächste Tür versteckt sich im halbdunkel einer alten Eiche. Soweit ihr erkennen könnt ist der obere Teil der Tür mit einer wundersamen Schnitzerei verziert.",
Müsste Halbdunkel nicht groß geschrieben sein?

2022-10-05 08:12 UTC, dnns01 commented on data/story.json
> +        "text": "Die nächste Tür die ihr anvisiert versteckt sich hinter einem hohen Schmiedeeisernem Tor mit spitzen Stacheln.",
"einem hohen Schmiedeeisernen Tor", oder?

2022-10-05 08:12 UTC, dnns01 commented on data/story.json
> +        "text": "Es öffnet eine Frau mit einem breiten Grinsen und lädt euch herein. \n Hinter ihr könnt ihr aber nur Dunkelheit und nichts Süßes erkennen. Dass sie insistiert, macht euch stutzig und
Hier müsste noch das Leerzeichen hinter dem \n und vor "Hinter ihr .." weg

2022-10-06 16:34 UTC, dnns01 approved these changes

2022-10-06 16:35 UTC, merged